SCREEN_WIDTH = 800 # These are my globals
SCREEN_HEIGHT = 600

BULLET_RADIUS = 11
BULLET_SPEED = 10
BULLET_LIFE = 60

SHIP_TURN_AMOUNT = 3
SHIP_THRUST_AMOUNT = 0.5
SHIP_RADIUS = 30
SHIP_LIVES = 5

INITIAL_ROCK_COUNT = 5

BIG_ROCK_SPIN = 1
BIG_ROCK_SPEED = 1.5
BIG_ROCK_RADIUS = 25

MEDIUM_ROCK_SPIN = -2
MEDIUM_ROCK_RADIUS = 7 # I changed this to make my game easier

SMALL_ROCK_SPIN = 5
SMALL_ROCK_RADIUS = 5 # I changed this to make my game easier